#ifndef RICTUS_INTELLIGENCE_ITEM_H
#define RICTUS_INTELLIGENCE_ITEM_H

#include <stddef.h>


#define RICTUS_INTELLIGENCE_ITEM_SOURCE_MAX \
    64

#define RICTUS_INTELLIGENCE_ITEM_TITLE_MAX \
    512

#define RICTUS_INTELLIGENCE_ITEM_URL_MAX \
    1024

#define RICTUS_INTELLIGENCE_ITEM_DATE_MAX \
    128

#define RICTUS_INTELLIGENCE_ITEM_SUMMARY_MAX \
    2048

#define RICTUS_INTELLIGENCE_ITEM_CONTENT_MAX \
    16384

#define RICTUS_INTELLIGENCE_ITEM_FINGERPRINT_MAX \
    32

#define RICTUS_INTELLIGENCE_ITEM_OBSERVED_MAX 64
#define RICTUS_INTELLIGENCE_ITEM_ROOT_SOURCE_MAX 128
#define RICTUS_INTELLIGENCE_ITEM_WHY_MAX 1024
#define RICTUS_INTELLIGENCE_ITEM_EVIDENCE_MAX 2048
#define RICTUS_INTELLIGENCE_ITEM_ASSESSMENT_MAX 2048
#define RICTUS_INTELLIGENCE_ITEM_UNKNOWNS_MAX 1024
#define RICTUS_INTELLIGENCE_ITEM_PROVENANCE_MAX 1024


typedef struct
{
    char source[
        RICTUS_INTELLIGENCE_ITEM_SOURCE_MAX
    ];

    char title[
        RICTUS_INTELLIGENCE_ITEM_TITLE_MAX
    ];

    char url[
        RICTUS_INTELLIGENCE_ITEM_URL_MAX
    ];

    char published[
        RICTUS_INTELLIGENCE_ITEM_DATE_MAX
    ];

    char summary[
        RICTUS_INTELLIGENCE_ITEM_SUMMARY_MAX
    ];

    char content[
        RICTUS_INTELLIGENCE_ITEM_CONTENT_MAX
    ];

    char fingerprint[
        RICTUS_INTELLIGENCE_ITEM_FINGERPRINT_MAX
    ];

    char observed[RICTUS_INTELLIGENCE_ITEM_OBSERVED_MAX];
    char root_source[RICTUS_INTELLIGENCE_ITEM_ROOT_SOURCE_MAX];
    char why_stn_labz_cares[RICTUS_INTELLIGENCE_ITEM_WHY_MAX];
    char evidence[RICTUS_INTELLIGENCE_ITEM_EVIDENCE_MAX];
    char assessment[RICTUS_INTELLIGENCE_ITEM_ASSESSMENT_MAX];
    char unknowns[RICTUS_INTELLIGENCE_ITEM_UNKNOWNS_MAX];
    char provenance[RICTUS_INTELLIGENCE_ITEM_PROVENANCE_MAX];

} rictus_intelligence_item_t;


#endif
