#include "collector.h"
#include <curl/curl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef struct { char *body; size_t length; int too_large; } buffer_t;
static size_t receive_body(char *data,size_t size,size_t count,void *context){buffer_t *b=context;size_t bytes=size*count;char *next;if(bytes>RICTUS_INTELLIGENCE_RESPONSE_MAX-b->length){b->too_large=1;return 0;}next=realloc(b->body,b->length+bytes+1);if(!next)return 0;b->body=next;memcpy(b->body+b->length,data,bytes);b->length+=bytes;b->body[b->length]='\0';return bytes;}
void rictus_intelligence_response_free(rictus_intelligence_response_t *r){if(!r)return;free(r->body);memset(r,0,sizeof(*r));}
rictus_intelligence_collect_result_t rictus_intelligence_collect(const rictus_intelligence_source_definition_t *s,rictus_intelligence_response_t *r){CURL *curl;CURLcode code;buffer_t b={0};char url[2048];long status=0;if(!s||!r||!s->host||!s->path)return RICTUS_INTELLIGENCE_COLLECT_INVALID_ARGUMENT;memset(r,0,sizeof(*r));if(snprintf(url,sizeof(url),"https://%s%s",s->host,s->path)<=0)return RICTUS_INTELLIGENCE_COLLECT_INVALID_ARGUMENT;curl=curl_easy_init();if(!curl)return RICTUS_INTELLIGENCE_COLLECT_SESSION_FAILED;curl_easy_setopt(curl,CURLOPT_URL,url);curl_easy_setopt(curl,CURLOPT_USERAGENT,"STN-LABZ-Rictus-Intelligence/0.17");curl_easy_setopt(curl,CURLOPT_FOLLOWLOCATION,1L);curl_easy_setopt(curl,CURLOPT_MAXREDIRS,5L);curl_easy_setopt(curl,CURLOPT_CONNECTTIMEOUT,15L);curl_easy_setopt(curl,CURLOPT_TIMEOUT,45L);curl_easy_setopt(curl,CURLOPT_SSL_VERIFYPEER,1L);curl_easy_setopt(curl,CURLOPT_SSL_VERIFYHOST,2L);curl_easy_setopt(curl,CURLOPT_ACCEPT_ENCODING,"");curl_easy_setopt(curl,CURLOPT_WRITEFUNCTION,receive_body);curl_easy_setopt(curl,CURLOPT_WRITEDATA,&b);code=curl_easy_perform(curl);curl_easy_getinfo(curl,CURLINFO_RESPONSE_CODE,&status);curl_easy_cleanup(curl);if(code!=CURLE_OK){free(b.body);return b.too_large?RICTUS_INTELLIGENCE_COLLECT_TOO_LARGE:RICTUS_INTELLIGENCE_COLLECT_RECEIVE_FAILED;}if(status<200||status>=300){free(b.body);r->http_status=(unsigned long)status;return RICTUS_INTELLIGENCE_COLLECT_HTTP_STATUS;}r->body=b.body;r->body_length=b.length;r->http_status=(unsigned long)status;return RICTUS_INTELLIGENCE_COLLECT_OK;}
const char *rictus_intelligence_collect_result_string(rictus_intelligence_collect_result_t r){static const char *const n[]={"ok","invalid argument","session failed","connect failed","request failed","send failed","receive failed","http status","response too large","memory failed"};return(unsigned)r<sizeof(n)/sizeof(n[0])?n[r]:"unknown";}
