#include <stdio.h>
#include <string.h>
#include <strings.h>
#include "doctrine.h"
#define COUNT(a) (sizeof(a)/sizeof((a)[0]))
static const rictus_intelligence_indicator_t boundaries[]={{1U,"CHAOS-CORE-MAILER","/app/core/mailer.php",RICTUS_INTELLIGENCE_SEVERITY_HIGH,RICTUS_INTELLIGENCE_HANDLING_OPERATOR_PM,1},{1U,"CHAOS-CORE-CONFIG","/app/core/config.php",RICTUS_INTELLIGENCE_SEVERITY_HIGH,RICTUS_INTELLIGENCE_HANDLING_OPERATOR_PM,1}};
static const char *const cms[]={"wordpress","wp-admin","wp-login","wp-content","wp-includes","joomla","administrator/index.php","drupal"};
static const rictus_intelligence_requirement_t requirements[]={
 {1U,"IR-001",1U,"Warn when owned ChAoS MVC protected boundaries are targeted.","ChAoS MVC core","One normalized protected-boundary observation.","standing",1},
 {1U,"IR-002",1U,"Detect evidence that Sentinel protection was bypassed or compromise occurred.","STN-LABZ fleet","Verified access, execution, exposure, persistence, or state change.","standing",1},
 {1U,"IR-003",2U,"Identify material patterns across distinct STN-LABZ sensors.","STN-LABZ fleet","Pattern confirmed across identified sensors without inflating source independence.","standing",1},
 {1U,"IR-004",2U,"Determine whether authoritative vulnerability reporting applies to deployed STN-LABZ technology.","Deployed software","Root-source affected versions matched to an inventory boundary.","standing",1},
 {1U,"IR-005",3U,"Measure whether collection sources answer requirements on time and uniquely.","Collection system","Timeliness, failures, duplication, and unique contribution are measurable.","standing",1}};
static const rictus_intelligence_information_requirement_t questions[]={
 {1U,"SIR-001","IR-001","Did a normalized request hit a registered ChAoS MVC path?","STN-LABZ sensor",0},
 {1U,"SIR-002","IR-002","Did Sentinel report success, failure, or a material state change?","STN-LABZ sensor",1},
 {1U,"SIR-003","IR-003","Which distinct site and sensor identities observed the same pattern?","STN-LABZ sensor",1},
 {1U,"SIR-004","IR-004","Does the authoritative affected-version range intersect deployed inventory?","authoritative root",1},
 {1U,"SIR-005","IR-005","Which sources are late, failing, duplicate-only, or uniquely useful?","collection telemetry",0}};
static int has_ci(const char *s,const char *n){size_t z;const char *p;if(!s||!n||!*n)return 0;z=strlen(n);for(p=s;*p;++p)if(strncasecmp(p,n,z)==0)return 1;return 0;}
static int item_has(const rictus_intelligence_item_t *i,const char *n){return has_ci(i->title,n)||has_ci(i->summary,n)||has_ci(i->content,n)||has_ci(i->evidence,n);}
size_t rictus_intelligence_protected_boundary_count(void){return COUNT(boundaries);}
const rictus_intelligence_indicator_t *rictus_intelligence_protected_boundary_get(size_t i){return i<COUNT(boundaries)?&boundaries[i]:NULL;}
size_t rictus_intelligence_requirement_count(void){return COUNT(requirements);}
const rictus_intelligence_requirement_t *rictus_intelligence_requirement_get(size_t i){return i<COUNT(requirements)?&requirements[i]:NULL;}
const rictus_intelligence_information_requirement_t *rictus_intelligence_information_requirement_get(size_t i){return i<COUNT(questions)?&questions[i]:NULL;}
int rictus_intelligence_source_evaluate(const rictus_intelligence_item_t *i,rictus_intelligence_source_evaluation_t *r){if(!i||!r)return 0;memset(r,0,sizeof(*r));r->schema_version=1U;if(strcasecmp(i->source,"STN-LABZ Threat API")==0){r->role=RICTUS_INTELLIGENCE_SOURCE_ROLE_SENSOR;r->independence=RICTUS_INTELLIGENCE_INDEPENDENCE_SAME_SENSOR_NETWORK;r->sensor_count=1U;}else if(strcasecmp(i->source,"CERT/CC Vulnerability Notes")==0)r->role=RICTUS_INTELLIGENCE_SOURCE_ROLE_DISCOVERY;else{r->role=RICTUS_INTELLIGENCE_SOURCE_ROLE_AUTHORITATIVE_ROOT;r->independence=RICTUS_INTELLIGENCE_INDEPENDENCE_INDEPENDENT;r->independent_source_count=1U;}return 1;}
int rictus_intelligence_warning_evaluate(const rictus_intelligence_item_t *i,rictus_intelligence_warning_t *r){size_t x;if(!i||!r)return 0;memset(r,0,sizeof(*r));r->schema_version=1U;r->handling=RICTUS_INTELLIGENCE_HANDLING_RETAIN;if(strcasecmp(i->source,"STN-LABZ Threat API")!=0){snprintf(r->reason, sizeof(r->reason), "%s", "External reporting requires environment-specific warning evidence.");return 1;}if(item_has(i,"sentinel bypass")||item_has(i,"successful unauthorized access")||item_has(i,"unauthorized execution")||item_has(i,"sensitive response content")||item_has(i,"persistence established")||item_has(i,"material state change")){r->severity=RICTUS_INTELLIGENCE_SEVERITY_CRITICAL;r->confidence=RICTUS_INTELLIGENCE_CONFIDENCE_HIGH;r->handling=RICTUS_INTELLIGENCE_HANDLING_CHANNEL_AND_ACK;r->automatic_reporting_authorized=1;snprintf(r->indicator_id, sizeof(r->indicator_id), "%s", "CHAOS-MATERIAL-COMPROMISE");snprintf(r->reason, sizeof(r->reason), "%s", "First-party telemetry explicitly reports bypass, unauthorized effect, exposure, persistence, or material state change; CRITICAL warning and acknowledgment are required.");return 1;}for(x=0;x<COUNT(boundaries);++x)if(item_has(i,boundaries[x].normalized_value)){r->severity=RICTUS_INTELLIGENCE_SEVERITY_HIGH;r->confidence=RICTUS_INTELLIGENCE_CONFIDENCE_HIGH;r->handling=RICTUS_INTELLIGENCE_HANDLING_OPERATOR_PM;r->protected_boundary_hit=1;r->automatic_reporting_authorized=1;snprintf(r->indicator_id, sizeof(r->indicator_id), "%s", boundaries[x].id);snprintf(r->reason,sizeof(r->reason),"Protected ChAoS MVC boundary %s hit; operator visibility is authorized, lifecycle escalation is not.",boundaries[x].normalized_value);return 1;}r->severity=RICTUS_INTELLIGENCE_SEVERITY_LOW;r->confidence=RICTUS_INTELLIGENCE_CONFIDENCE_HIGH;for(x=0;x<COUNT(cms);++x)if(item_has(i,cms[x])){snprintf(r->reason, sizeof(r->reason), "%s", "Blocked commodity CMS probing is capped LOW.");return 1;}snprintf(r->reason, sizeof(r->reason), "%s", "Perimeter-handled sensor activity with no protected-boundary evidence.");return 1;}
const char *rictus_intelligence_severity_string(rictus_intelligence_severity_t s){switch(s){case RICTUS_INTELLIGENCE_SEVERITY_INFORMATIONAL:return "INFORMATIONAL";case RICTUS_INTELLIGENCE_SEVERITY_LOW:return "LOW";case RICTUS_INTELLIGENCE_SEVERITY_HIGH:return "HIGH";case RICTUS_INTELLIGENCE_SEVERITY_CRITICAL:return "CRITICAL";default:return "INVALID";}}
